"""add_operating_costs_table

Revision ID: 1394f2656d53
Revises: 5f003722d7b8
Create Date: 2026-03-31 12:26:52.490770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1394f2656d53'
down_revision: Union[str, None] = '5f003722d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_forecasts',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('best_case_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('worst_case_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('prophet_lower', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('prophet_upper', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('mae', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('mape', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_forecasts_pair'), 'fx_forecasts', ['pair'], unique=False)
    op.create_table('operating_costs',
    sa.Column('cost_name', sa.String(length=255), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', name='costfrequency'), nullable=False),
    sa.Column('monthly_equivalent', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('category', sa.Enum('RENT', 'UTILITIES', 'SALARIES', 'TRANSPORT', 'MARKETING', 'OTHER', name='costcategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operating_costs')
    op.drop_index(op.f('ix_fx_forecasts_pair'), table_name='fx_forecasts')
    op.drop_table('fx_forecasts')
    # ### end Alembic commands ###
