"""add_migration_v2_columns

Revision ID: 5ee86806d6dc
Revises: 909af0446a63
Create Date: 2026-07-01 17:49:09.684847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee86806d6dc'
down_revision: Union[str, None] = '909af0446a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('tax_amount', sa.Numeric(precision=18, scale=6), nullable=True))
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=False)
    # Extend movementtype PostgreSQL enum with new values
    op.execute("ALTER TYPE movementtype ADD VALUE IF NOT EXISTS 'stock_adjustment'")
    op.execute("ALTER TYPE movementtype ADD VALUE IF NOT EXISTS 'opening_stock'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_column('sales', 'tax_amount')
    op.drop_column('sales', 'invoice_number')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'barcode')
    # Note: PostgreSQL does not support removing enum values; downgrade is partial
    # ### end Alembic commands ###
