"""initial_schema

Revision ID: 5f003722d7b8
Revises: 
Create Date: 2026-03-30 20:45:48.732190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f003722d7b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_subsidy_analyses',
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('portfolio_total_margin', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('subsidy_matrix', sa.JSON(), nullable=True),
    sa.Column('high_margin_products', sa.JSON(), nullable=True),
    sa.Column('low_margin_products', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dscr_records',
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('net_operating_income', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_debt_service', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('dscr_value', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_below_threshold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_exposures',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('total_exposure_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('locked_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('locked_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('floating_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.Enum('CBN_OFFICIAL', 'PARALLEL_MARKET', 'MANUAL', 'API_PROVIDER', name='ratesource'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_pair'), 'fx_rates', ['pair'], unique=False)
    op.create_table('loan_obligations',
    sa.Column('lender_name', sa.String(length=255), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('MONTHLY', 'QUARTERLY', name='paymentfrequency'), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SETTLED', 'DEFAULTED', name='loanstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_recommendations',
    sa.Column('category', sa.Enum('PRICING', 'INVENTORY', 'FX', 'CASHFLOW', 'ORDERS', name='recommendationcategory'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='recommendationpriority'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_impact', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.Enum('PRICE_CHANGE', 'REORDER', 'FX_LOCK', 'COST_CUT', 'USD_PURCHASE', name='actiontype'), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DISMISSED', 'EXPIRED', 'APPLIED', name='recommendationstatus'), nullable=False),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflow_projections',
    sa.Column('projection_date', sa.Date(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('monthly_buckets', sa.JSON(), nullable=True),
    sa.Column('total_inflows', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_outflows', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_alerts',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('direction', sa.Enum('ABOVE', 'BELOW', name='alertdirection'), nullable=False),
    sa.Column('threshold_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_exposure_configs',
    sa.Column('locked_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('floating_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_simulation_runs',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('num_simulations', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('mean_projected_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('p5_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('p50_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('p95_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('var_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('distribution_data', sa.JSON(), nullable=True),
    sa.Column('run_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_payment_schedules',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('projection_assumptions',
    sa.Column('revenue_growth_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('seasonality_factors', sa.JSON(), nullable=True),
    sa.Column('fx_rate_assumption', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_inflation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PRODUCTION', 'SHIPPING', 'CLEARED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_at_creation', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_order_number'), 'purchase_orders', ['order_number'], unique=True)
    op.create_table('reorder_configs',
    sa.Column('default_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('service_level_target', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('demand_lookback_days', sa.Integer(), nullable=False),
    sa.Column('holding_cost_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_bulk_upload_jobs',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='uploadjobstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usd_strategy_configs',
    sa.Column('target_usd_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_usd_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='risktolerance'), nullable=False),
    sa.Column('max_single_purchase_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preferred_rate_percentile', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_elasticities',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('elasticity_coefficient', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('r_squared', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('data_points_used', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('price_range_min', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price_range_max', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('demand_curve_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('inventory_levels',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('last_replenished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('low_stock_alerts',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margin_targets',
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('set_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_line_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_payments',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'LC', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'VOIDED', name='paymentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('transitioned_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['transitioned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('old_unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('new_unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('old_selling_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('new_selling_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_recommendations',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('expected_demand_change_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_revenue_change_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_margin_change_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'REJECTED', 'EXPIRED', name='recommendationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reorder_suggestions',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('suggested_order_quantity', sa.Integer(), nullable=False),
    sa.Column('economic_order_quantity', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('avg_daily_demand', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('demand_variability', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('estimated_stockout_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISMISSED', 'CONVERTED_TO_ORDER', name='reorderstatus'), nullable=False),
    sa.Column('converted_order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['converted_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.Enum('ONLINE', 'RETAIL', 'WHOLESALE', name='salechannel'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'VOIDED', 'PENDING', name='salestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_table('stock_movements',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('SALE_DEPLETION', 'SALE_REVERSAL', 'MANUAL_ADD', 'MANUAL_REMOVE', 'ORDER_RECEIVED', 'DAMAGED', name='movementtype'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_scenarios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('revenue_shock_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fx_shock_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_shock_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_projection_id', sa.Uuid(), nullable=False),
    sa.Column('stressed_buckets', sa.JSON(), nullable=True),
    sa.Column('stressed_dscr', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('stressed_runway_months', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_projection_id'], ['cashflow_projections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usd_purchase_schedules',
    sa.Column('strategy_config_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_date', sa.Date(), nullable=False),
    sa.Column('recommended_amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('recommended_rate_ceiling', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'EXECUTED', 'SKIPPED', 'EXPIRED', name='purchaseschedulestatus'), nullable=False),
    sa.Column('executed_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('executed_amount_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['usd_strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_audit_entries',
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_changes', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_audit_entries')
    op.drop_table('usd_purchase_schedules')
    op.drop_table('stress_scenarios')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('reorder_suggestions')
    op.drop_table('pricing_recommendations')
    op.drop_table('price_history')
    op.drop_table('order_status_history')
    op.drop_table('order_payments')
    op.drop_table('order_line_items')
    op.drop_table('margin_targets')
    op.drop_table('low_stock_alerts')
    op.drop_table('inventory_levels')
    op.drop_table('demand_elasticities')
    op.drop_table('usd_strategy_configs')
    op.drop_table('sale_bulk_upload_jobs')
    op.drop_table('reorder_configs')
    op.drop_index(op.f('ix_purchase_orders_order_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('projection_assumptions')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('loan_payment_schedules')
    op.drop_table('fx_simulation_runs')
    op.drop_table('fx_exposure_configs')
    op.drop_table('fx_alerts')
    op.drop_table('cashflow_projections')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('product_categories')
    op.drop_table('loan_obligations')
    op.drop_index(op.f('ix_fx_rates_pair'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('fx_exposures')
    op.drop_table('dscr_records')
    op.drop_table('cross_subsidy_analyses')

    # Drop PostgreSQL enum types created during upgrade
    for enum_name in [
        'purchaseschedulestatus', 'reorderstatus', 'salechannel', 'salestatus',
        'movementtype', 'alertstatus', 'uploadjobstatus', 'paymentmethod',
        'paymentstatus', 'orderstatus', 'recommendationstatus', 'actiontype',
        'recommendationpriority', 'recommendationcategory', 'risktolerance',
        'ratesource', 'alertdirection', 'paymentfrequency', 'loanstatus',
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
