"""add_customer_payment_fields_to_sales

Revision ID: 6f6e21964f05
Revises: 847bad16c5c9
Create Date: 2026-06-06 08:09:40.772383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6e21964f05'
down_revision: Union[str, None] = '847bad16c5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('products', 'image_url')
    op.add_column('sales', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'contact_number')
    op.drop_column('sales', 'customer_name')
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
