"""add_business_profile_app_settings_location_enhancements

Revision ID: a46ec11f3501
Revises: 36e556663d21
Create Date: 2026-07-02 05:22:39.239521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46ec11f3501'
down_revision: Union[str, None] = '36e556663d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('business_profile',
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('timezone', sa.String(length=60), server_default='Africa/Lagos', nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_start_day', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.add_column('business_locations', sa.Column('timezone', sa.String(length=60), server_default='Africa/Lagos', nullable=False))
    op.add_column('business_locations', sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False))
    op.add_column('business_locations', sa.Column('tax_number', sa.String(length=100), nullable=True))
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE locationtype AS ENUM ('retail', 'warehouse', 'online');
        EXCEPTION WHEN duplicate_object THEN null;
        END $$;
    """)
    op.add_column('business_locations', sa.Column('location_type', sa.Enum('retail', 'warehouse', 'online', name='locationtype', create_type=False), nullable=True))
    op.add_column('business_locations', sa.Column('is_pos_location', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('business_locations', sa.Column('pos_location_id', sa.String(length=50), nullable=True))
    # paytermtype already exists in the DB as a VARCHAR; skip altering it here
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_locations', 'pos_location_id')
    op.drop_column('business_locations', 'is_pos_location')
    op.drop_column('business_locations', 'location_type')
    op.execute("DROP TYPE IF EXISTS locationtype")
    op.drop_column('business_locations', 'tax_number')
    op.drop_column('business_locations', 'currency')
    op.drop_column('business_locations', 'timezone')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('business_profile')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
