"""add_image_url_nullable_category_products

Revision ID: c47911aa433e
Revises: 1394f2656d53
Create Date: 2026-03-31 13:30:58.083077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47911aa433e'
down_revision: Union[str, None] = '1394f2656d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
