"""add_sell_return_and_sale_location_id

Revision ID: c93d90eaa01a
Revises: f4a5b6c7d8e9
Create Date: 2026-06-23 17:20:08.468815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93d90eaa01a'
down_revision: Union[str, None] = 'f4a5b6c7d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sell_returns',
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sell_returns_sale_id'), 'sell_returns', ['sale_id'], unique=False)
    op.drop_index('ix_stock_count_items_product_id', table_name='stock_count_items')
    op.drop_index('ix_stock_count_items_stock_count_id', table_name='stock_count_items')
    op.drop_table('stock_count_items')
    op.drop_index('ix_stock_counts_created_at', table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index('ix_user_api_keys_user_id', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_table('invoice_schemes')
    op.drop_constraint('uq_business_locations_location_code', 'business_locations', type_='unique')
    op.drop_index('ix_price_suggestions_suggested_at', table_name='price_suggestions')
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_constraint('uq_products_slug', 'products', type_='unique')
    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_index('ix_purchase_returns_order_id', table_name='purchase_returns')
    op.create_index(op.f('ix_purchase_returns_original_order_id'), 'purchase_returns', ['original_order_id'], unique=False)
    op.add_column('sales', sa.Column('location_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sales_location_id'), 'sales', ['location_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'business_locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_location_id'), table_name='sales')
    op.drop_column('sales', 'location_id')
    op.drop_index(op.f('ix_purchase_returns_original_order_id'), table_name='purchase_returns')
    op.create_index('ix_purchase_returns_order_id', 'purchase_returns', ['original_order_id'], unique=False)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    op.create_unique_constraint('uq_products_slug', 'products', ['slug'])
    op.drop_column('products', 'image_url')
    op.create_index('ix_price_suggestions_suggested_at', 'price_suggestions', ['suggested_at'], unique=False)
    op.create_unique_constraint('uq_business_locations_location_code', 'business_locations', ['location_code'])
    op.create_table('invoice_schemes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scheme_type', postgresql.ENUM('blank', 'year', name='schemetype'), server_default=sa.text("'blank'::schemetype"), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('start_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('total_digits', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('next_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='invoice_schemes_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_schemes_pkey')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('encrypted_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_api_keys_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_api_keys_pkey')
    )
    op.create_index('ix_user_api_keys_user_id', 'user_api_keys', ['user_id'], unique=False)
    op.create_table('stock_counts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('count_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('count_type', postgresql.ENUM('PRODUCT', 'LOT', name='stockcounttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'FINALIZED', name='stockcountstatus'), server_default=sa.text("'DRAFT'::stockcountstatus"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finalized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='stock_counts_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_counts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stock_counts_created_at', 'stock_counts', ['created_at'], unique=False)
    op.create_table('stock_count_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_count_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_line_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('system_quantity_at_count', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('counted_quantity', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_line_item_id'], ['order_line_items.id'], name='stock_count_items_order_line_item_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_count_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_counts.id'], name='stock_count_items_stock_count_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_count_items_pkey')
    )
    op.create_index('ix_stock_count_items_stock_count_id', 'stock_count_items', ['stock_count_id'], unique=False)
    op.create_index('ix_stock_count_items_product_id', 'stock_count_items', ['product_id'], unique=False)
    op.drop_index(op.f('ix_sell_returns_sale_id'), table_name='sell_returns')
    op.drop_table('sell_returns')
    # ### end Alembic commands ###
