"""re_nullable_products_category_id

Revision ID: e1f2a3b4c5d6
Revises: aaf1881e3f19
Create Date: 2026-07-10 22:10:00.000000

products.category_id was made nullable by c47911aa433e
(add_image_url_nullable_category_products), but a later autogenerated
migration -- 6f6e21964f05 (add_customer_payment_fields_to_sales) -- was
generated against a stale model snapshot and silently reverted it back to
NOT NULL (and dropped image_url, restored separately in aaf1881e3f19). The
ORM model (products/models.py) and API schema have declared category_id
Optional the whole time, so this just re-aligns the DB with what the app
has always assumed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f2a3b4c5d6'
down_revision: Union[str, None] = 'aaf1881e3f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('products', 'category_id', existing_type=sa.UUID(), nullable=True)


def downgrade() -> None:
    op.alter_column('products', 'category_id', existing_type=sa.UUID(), nullable=False)
